{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pingora-reverse-proxy.fullname" $ }}-{{ $name }}
  labels:
    {{- include "pingora-reverse-proxy.labels" $ | nindent 4 }}
  {{- with $service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $service.type }}
  ports:
    - name: {{ $name }}
      port: {{ $service.port }}
      targetPort: {{ $name }}
      protocol: TCP
  selector:
    {{- include "pingora-reverse-proxy.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
